version: '3.0'

services:
  waha:
    image: devlikeapro/waha:latest
    restart: always
    ports:
      - "3000:3000"
    environment:
      WHATSAPP_DEFAULT_ENGINE: 'WEBJS'
      WHATSAPP_START_SESSION: 'default'
    volumes:
      - ./waha_sessions:/app/sessions
